# Generated by Django 5.1.2 on 2024-10-16 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.CharField(default='N/A', max_length=200)),
                ('numero_identificacion_vehiculo', models.CharField(default='N/A', max_length=17)),
                ('anio_fabricacion_vehiculo', models.PositiveIntegerField(default=2000)),
                ('modelo_vehiculo', models.CharField(default='N/A', max_length=100)),
                ('marca_vehiculo', models.CharField(default='N/A', max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tipo_cliente', models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='cliente.tipocliente')),
            ],
        ),
    ]
