# Generated by Django 5.1.2 on 2024-10-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='anio_fabricacion_vehiculo',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='marca_vehiculo',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='modelo_vehiculo',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_identificacion_vehiculo',
            field=models.CharField(default='N/A', max_length=17),
        ),
    ]
