# Generated by Django 5.1.2 on 2024-10-16 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='anio_fabricacion_vehiculo',
            new_name='año_fabricación_vehículo',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='direccion',
            new_name='dirección',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='marca_vehiculo',
            new_name='marca_vehículo',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='modelo_vehiculo',
            new_name='modelo_vehículo',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='numero_identificacion_vehiculo',
            new_name='número_identificación_vehículo',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='telefono',
            new_name='teléfono',
        ),
    ]
